### ISSUE TITLE
How to do a rule within a rule

### ISSUE THREAD

**Issue by Aareon** [Liamraystanley/Code#108]
I'm using @hook's rule ability to find a string within comments. However, now I am attempting to get a command sent just prior to finding my rule. Please help.

**Comment by Liamraystanley** [comment]
Can you clarify what you are attempting to accomplish/provide the code you are currently using?

**Comment by Aareon** [comment]
Hi, I'm trying to get the message from a channel tipbot that a tip has been
sent, then I want to read the line before it where the user declared the
tip along with parameters that follow.

**Comment by Liamraystanley** [comment]
Hm, alright. There are a few things you could do in that case.

#### "code.logs" route:

`code.logs['channel']` is a dictionary of channel keys, with the value being a array of dictionaries. For example:

```python
{
    "#example": [
        {
            "message": "your message here",
            "nick": "somebot",
            "time": 1448847813,
            "channel": "#example"
        },
        {
            "message": ".some command here",
            "nick": "myircnick",
            "time": 1448847818,
            "channel": "#example"
        }
    ]
}
```

You will likely want to run through the list, find the message you are triggering on, and see if there is a message before it.

#### "code.chan" route:

With this route, you can access a very short backlog from a specific user. For example:

```python
def myfunc(code, input):
    user = code.chan["#example"]["Someuser"]
    # user would look something like:
    {
        'normal': True,
        'voiced': False,
        'op': False,
        'count': 24,
        'messages': [
            {
                'time': 1448847813,
                'message': "This is my mesage"
            },
            {
                'time': 1448847818,
                'message': "And this is another"
            }
        ]
    }
```

#### Else:

Otherwise, if the two above do not suffice, you may just want to have a single event listener. If it doesn't match the specific string you are looking for, dump it into storage. Once one does match, you can just reference your storage, and find the message that was right before it.

Is that what you were looking for?

**Comment by Aareon** [comment]
How do I go about putting 'messages' into a variable. Sorry, I'm still a
python newbie. I'm trying hard to understand how this works and have done
everything I can think of.

**Comment by Liamraystanley** [comment]
Did you still need assistance with getting this setup?

**Comment by Aareon** [comment]
Answered. Thank you.
